/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Presentacion;

import Datos.Varticulo;
import Logica.Farticulo;
import java.sql.Date;
import java.util.Calendar;
import javax.swing.JOptionPane;

/**
 *
 * @author Cesar Castillo
 */
public class FrmRegistrarArticulos extends javax.swing.JInternalFrame {

    /**
     * Creates new form FrmCliente
     */
    public FrmRegistrarArticulos() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Centro = new javax.swing.JPanel();
        cajaCodigo = new javax.swing.JTextField();
        cajaDescripcion = new javax.swing.JTextField();
        cajaPrecioContado = new javax.swing.JTextField();
        cajaPrecioLista = new javax.swing.JTextField();
        cajaStock = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        cajaTalle = new javax.swing.JTextField();
        dcFecha_alta = new com.toedter.calendar.JDateChooser();
        cboCategoria = new javax.swing.JComboBox();
        Norte = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        Sur = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setTitle("Registrar Articulos");

        Centro.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        Centro.add(cajaCodigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(123, 21, 81, -1));
        Centro.add(cajaDescripcion, new org.netbeans.lib.awtextra.AbsoluteConstraints(123, 52, 165, -1));
        Centro.add(cajaPrecioContado, new org.netbeans.lib.awtextra.AbsoluteConstraints(123, 114, 218, -1));
        Centro.add(cajaPrecioLista, new org.netbeans.lib.awtextra.AbsoluteConstraints(123, 145, 218, -1));
        Centro.add(cajaStock, new org.netbeans.lib.awtextra.AbsoluteConstraints(123, 176, 79, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setText("Codigo :");
        Centro.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(69, 24, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel3.setText("Descripcion :");
        Centro.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(42, 55, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel4.setText("Talle :");
        Centro.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 86, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel5.setText("Precio Contado :");
        Centro.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(22, 117, -1, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel6.setText("Stock :");
        Centro.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(75, 179, -1, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel7.setText("Categoria :");
        Centro.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(52, 211, -1, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel8.setText("Fecha de Alta :");
        Centro.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(31, 245, -1, -1));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel9.setText("Precio Lista :");
        Centro.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(42, 148, -1, -1));
        Centro.add(cajaTalle, new org.netbeans.lib.awtextra.AbsoluteConstraints(123, 83, 80, -1));
        Centro.add(dcFecha_alta, new org.netbeans.lib.awtextra.AbsoluteConstraints(123, 239, 165, -1));

        cboCategoria.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        Centro.add(cboCategoria, new org.netbeans.lib.awtextra.AbsoluteConstraints(123, 205, 218, -1));

        getContentPane().add(Centro, java.awt.BorderLayout.CENTER);

        Norte.setBackground(new java.awt.Color(204, 0, 51));

        jLabel1.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Registrar");

        javax.swing.GroupLayout NorteLayout = new javax.swing.GroupLayout(Norte);
        Norte.setLayout(NorteLayout);
        NorteLayout.setHorizontalGroup(
            NorteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(NorteLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(162, Short.MAX_VALUE))
        );
        NorteLayout.setVerticalGroup(
            NorteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(NorteLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(NorteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(NorteLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(0, 10, Short.MAX_VALUE))
                    .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        getContentPane().add(Norte, java.awt.BorderLayout.PAGE_START);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/add_1.png"))); // NOI18N
        jButton1.setText("Nuevo");

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/database_1.png"))); // NOI18N
        jButton2.setText("Guardar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/remove_1.png"))); // NOI18N
        jButton3.setText("Salir");

        javax.swing.GroupLayout SurLayout = new javax.swing.GroupLayout(Sur);
        Sur.setLayout(SurLayout);
        SurLayout.setHorizontalGroup(
            SurLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SurLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jButton1)
                .addGap(18, 18, 18)
                .addComponent(jButton2)
                .addGap(18, 18, 18)
                .addComponent(jButton3)
                .addContainerGap(17, Short.MAX_VALUE))
        );
        SurLayout.setVerticalGroup(
            SurLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SurLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(SurLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2)
                    .addComponent(jButton3))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(Sur, java.awt.BorderLayout.PAGE_END);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed

        Varticulo dts = new Varticulo();
        Farticulo func = new Farticulo();

        dts.setArticulo_codigo(cajaCodigo.getText());
        dts.setArticulo_descripcion(cajaDescripcion.getText());
        dts.setArticulo_talle(cajaTalle.getText());
        dts.setArticulo_precio_contado(Double.parseDouble(cajaPrecioContado.getText()));
        dts.setArticulo_precio_lista(Double.parseDouble(cajaPrecioLista.getText()));
        dts.setArticulo_stock(Integer.parseInt(cajaStock.getText()));

        int seleccion = cboCategoria.getSelectedIndex();
        dts.setArticulo_categoria((seleccion + 1));

        Calendar cal;
        int dia, mes, año;
        cal = dcFecha_alta.getCalendar();
        dia = cal.get(Calendar.DAY_OF_MONTH);
        mes = cal.get(Calendar.MONTH);
        año = cal.get(Calendar.YEAR) - 1900;

        dts.setArticulo_fecha_alta(new Date(año, mes, dia));
        
        if (func.insertar(dts)) {
            JOptionPane.showMessageDialog(rootPane, "Cliente Insertado");
            //limpiar();
            //inhabilitar();
        }

        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Centro;
    private javax.swing.JPanel Norte;
    private javax.swing.JPanel Sur;
    private javax.swing.JTextField cajaCodigo;
    private javax.swing.JTextField cajaDescripcion;
    private javax.swing.JTextField cajaPrecioContado;
    private javax.swing.JTextField cajaPrecioLista;
    private javax.swing.JTextField cajaStock;
    private javax.swing.JTextField cajaTalle;
    private javax.swing.JComboBox cboCategoria;
    private com.toedter.calendar.JDateChooser dcFecha_alta;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    // End of variables declaration//GEN-END:variables
}
